### PR TITLE
Make repo deprecated

### PR DESCRIPTION
**Pull request by techmexdev**

### CODE REVIEW

**Comment by hswolff** [comment]
Thanks for opening a PR! Curious as to your reasons for this?

**Comment by techmexdev** [comment]
Last commit was 5 years ago 😅

**Comment by hswolff** [comment]
Hah, but is it deprecated? It's just not maintained anymore. :D

**Comment by techmexdev** [comment]
Correct 😅

**Comment by hswolff** [comment]
Hey, thanks!

**Pull request merged**
